const errorCodes = {
    TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
    INVALID_TOKEN: "INVALID_TOKEN",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    FORBIDDEN: "FORBIDDEN",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    INCORRECT_CREDENTIAL: "INCORRECT_CREDENTIAL",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    MISSING_PARAMETERS: "MISSING_PARAMETERS",
    MISSING_DATA: "MISSING_DATA",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    DATA_INCORRECT_FORMAT: "DATA_INCORRECT_FORMAT",
    INVALID_DATA: "INVALID_DATA",
    DATA_ALREADY_EXISTS: "DATA_ALREADY_EXISTS",
    BOOK_NOT_BELONG_TO_READER: "BOOK_NOT_BELONG_TO_READER",
    BOOK_RETURNED: "BOOK_RETURNED",
    BORROW_LIMIT: "BORROW_LIMIT",
    BOOKS_ARE_LATE: "BOOKS_ARE_LATE",
    DATA_IS_BINDING: "DATA_IS_BINDING",
    BOOK_OUT_OF_STOCK: "BOOK_OUT_OF_STOCK",
};

module.exports = { errorCodes };
