const TABLE_NAME = {
    BOOK: "BOOK",
    BOOK_LOST: "BOOK_LOST",
    BOOK_REQUEST: "BOOK_REQUEST",
    POSITION: "POSITION",
    CATEGORY: "CATEGORY",
    LOAN_RECEIPT: "LOAN_RECEIPT",
    FINE_POLICY: "FINE_POLICY",
    FINE_POLICY_WITH_BOOK: "FINE_POLICY_WITH_BOOK",
    PENALTY_TICKET: "PENALTY_TICKET",
    SETTING: "SETTING",
    ACCOUNT: "ACCOUNT",
    USER: "USER",
    CARD_OPENING_FEE: "CARD_OPENING_FEE",
    BOOKING_BOOK_FORM: "BOOKING_BOOK_FORM",
    FIELD: "FIELD",
};

module.exports = { TABLE_NAME };
