const ACCESS_TOKEN_SECRET = "HJO2NKSPX234334";

const SECRET_KEY = "anhemiit@123";

const POSTGRES_DATABASE = "librarian";

const POSTGRES_USER = "postgres";

const POSTGRES_PASSWORD = "0000";

const POSTGRES_HOST = "localhost";

const POSTGRES_PORT = "5432";

module.exports = { ACCESS_TOKEN_SECRET, SECRET_KEY, POSTGRES_DATABASE, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT };
